blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ask-question$', views.ask_question, name='ask_question'),
    url(r'^answer/(?P<question_id>\d+)$', views.answer, name='answer'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^answer/upvote/(?P<question_id>\d+)$', views.upvote, name='upvote'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^stats$', views.stats, name='stats')
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    user = models.ForeignKey(User)
    question_text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

    class Meta:
        db_table = 'question'


class Answer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='question')
    answer_text = models.TextField()
    up_votes = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        db_table = 'answer'

dashboard/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm


class UserForm(ModelForm):
    class Meta:
        model = User
        widgets = {
            'password': forms.PasswordInput(),

        }
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max
from django.db import IntegrityError
from django.shortcuts import render, redirect
from .models import Question, Answer
from .forms import UserForm
from django.shortcuts import HttpResponse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from datetime import datetime, timedelta


def index(request):
    questions = Question.objects.all()
    return render(request,'dashboard/index.html', {'questions': questions})


@login_required
def ask_question(request):
    user = request.user
    print(request.user)
    if request.POST:
        question_asked = request.POST.get('question')
        question = Question()
        question.question_text = question_asked
        question.user = user
        question.save()
        return redirect('/')
    else:
        return render(request, 'dashboard/ask_questions.html')


@login_required
def answer(request, question_id):
    question = Question.objects.get(pk=question_id)
    user = request.user

    if request.POST:
        submitted_answer = request.POST.get('answer')
        answer_values = Answer()
        answer_values.question = question
        answer_values.answer_text = submitted_answer
        try:
            answer_values.save()
        except IntegrityError:
            return redirect('/')

    else:
        return render(request, 'dashboard/answer.html', {'question': question})
    return redirect('/')


@login_required
def profile(request):
    user = request.user
    answers_written = []
    questions = Question.objects.filter(user=user)
    for question in questions:
        answers = Answer.objects.filter(question=question).first()
        answers_written.append(answers)
    return render(request, 'dashboard/profile.html', {'user': user, 'questions': questions, 'answers': answers_written})


def register(request):
    if request.POST:
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user_name = user_form.cleaned_data['username']
            pass_word = user_form.cleaned_data['password']
            email = user_form.cleaned_data['email']
            user = User.objects.create_user(user_name, email, pass_word)
            user.save()
            user.first_name = user_form.cleaned_data['first_name']
            user.last_name = user_form.cleaned_data['last_name']
            user.save()
            return redirect('dashboard:login')
    else:
        user_form = UserForm()
    return render(request, 'dashboard/register.html', {'user_form': user_form})


def login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,
                            password=password)
        if user.is_authenticated:
            if user is not None and user.is_active:
                auth_login(request, user)
                return redirect('dashboard:index')
        return HttpResponse("Login Failed. Invalid username or password")
    else:
        return render(request, "dashboard/login.html")


def stats(request):
    hour_ago = datetime.now() - timedelta(hours=1)
    upvoted_answer = Answer.objects.filter(up_votes__gt=0, updated_on__gt=hour_ago).order_by('-up_votes')
    max = Answer.objects.all().aggregate(Max('up_votes'))
    upvote_max = max['up_votes__max']
    max_upvoted_answer = Answer.objects.filter(up_votes__exact=upvote_max)
    # print(max_upvoted_answer)
    return render(request, 'dashboard/stats.html', {'upvoted_last_hour': upvoted_answer, 'max_upvoted_answers': max_upvoted_answer})


@login_required
def upvote(request, question_id):
    answer = Answer.objects.get(question=question_id)
    answer.up_votes += 1
    answer.save()
    return redirect('/')


def logout(request):
    auth_logout(request)
    return redirect('dashboard:login')

dashboard/templates/dashboard/answer.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% block css_block %}

{% endblock %}

{% block body %}
    {% include 'dashboard/homepage_header.html' %}
    <div class="container">
        <h3></h3>
        <form method="post">
            {% csrf_token %}
            <textarea cols="100" rows="5" placeholder="Write Answer" name="answer"></textarea><br>
            <input type="submit" class="btn btn-primary ask-question" value="Submit Answer">
        </form>
    </div>
{% endblock %}

dashboard/templates/dashboard/ask_questions.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% block css_block %}

{% endblock %}

{% block body %}
    {% include 'dashboard/homepage_header.html' %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <textarea cols="100" rows="5" placeholder="Ask a Question" name="question"></textarea><br>
            <input type="submit" class="btn btn-primary ask-question">

        </form>
    </div>

{% endblock %}

dashboard/templates/dashboard/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>My Blog</title>

        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">

         <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- Custom CSS -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <!-- Custom JavaScript -->
        <script src="{% static 'js/script.js' %}"></script>

        <!-- Include Font Awesome -->
        <script src="https://use.fontawesome.com/6aa1176ce5.js"></script>

        {% block css_block %}
        {% endblock %}

    </head>

    <body id="page-top">

        {%  block header %}
        {%  endblock %}

        {% block body %}
        {% endblock %}



        {% block js_block %}
        {% endblock %}
    </body>
</html>

dashboard/templates/dashboard/homepage_header.html
{% load staticfiles %}

{% block header %}

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">WebSiteName</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="{% url 'dashboard:ask_question' %}">Ask a Question</a></li>
                <li><a href="{% url 'dashboard:profile' %}">My Profile</a></li>
                <li><a href="{% url 'dashboard:stats' %}">Dashboard Stats</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'dashboard:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                <li><a href="{% url 'dashboard:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                <li><a href="{% url 'dashboard:logout' %}"><span class="glyphicon glyphicon-log-outlog"></span> Log out</a></li>
            </ul>
        </div>
    </nav>

{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% block css_block %}

{% endblock %}

{% block body %}
    {% include 'dashboard/homepage_header.html' %}
    <div class="container">
        {% if questions is None %}
            <h3 class="text-success">Please Ask Questions and Write Answers to display here</h3>
        {% endif %}

        {% for question in questions %}
            <div class="card">
                <h4 class="card-header"> {{ question.question_text }} </h4><hr>
                <div class="card-block">
                    <p class="card-body">
                        <b>Answer: </b>{{ question.question.answer_text }} <br> <hr>
                    </p>
                    <p class="card-footer">
                        <div class="row">
                            <div class="col-md-3">
                                <a type="submit" class="btn btn-primary" href="{% url 'dashboard:answer' question.id %}">Answer</a>
                            </div>

                            <div class="col-md-9">
                                <a href="{% url 'dashboard:upvote' question.id %}" class="upvote-icon"><i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i><b> {{ question.question.up_votes }} </b></a>
                                <i class="fa fa-thumbs-down fa-2x" aria-hidden="true" style="color: #880000; padding-right: 80px"></i>
                                answered by: <b> {{ question.user.first_name }} </b>
                            </div>
                        </div>
                    </p>
                </div>
            </div><br><br>
        {% endfor %}
    </div>
{% endblock %}

dashboard/templates/dashboard/login.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}

{% block css_block %}

{% endblock %}

{% block body %}
    {% include 'dashboard/homepage_header.html' %}



<div class="top-content">
    <div class="inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2 text">
                    <h1>Login Form</h1>
                    <div class="description">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>Login to our site</h3>
                            <p>Enter your username and password to log in:</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-key"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form role="form" action="" method="post" class="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="form-username">Username</label>
                                <input type="text" name="username" placeholder="Username..." class="form-username form-control" id="form-username">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">Password</label>
                                <input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
                            </div>
                            <button type="submit" class="btn btn-primary">Sign in!</button>
                        </form>
                    </div>
                    <div>
                        <h5>New to site?</h5>
                        <a class="btn btn-block btn-success" href="{% url 'dashboard:register' %}">Register Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}


{% block body %}
    {% include 'dashboard/homepage_header.html' %}
    <div class="container">
        <h4>Hi, {{ user.first_name }}</h4>
        <a class="btn btn-success" href="{% url 'dashboard:logout' %}">Log out</a>
        <h3 class="text-success">See all of your Questions Asked, Answers Written and your up voted Answers </h3>
        <h3>Questions Asked by me</h3>
        <div>
            {% for question in questions %}
                <div class="card">
                    <h4 class="card-header"> {{ question.question_text }} </h4>
                </div><br>
            {% endfor %}
            <h3>Answers written by me</h3>
            <p>
                {% for answer in answers %}
                    {% if answer is not None %}
                        <h4 class="card">Question: {{ answer.question.question_text }}<br><br>
                            Answer: {{ answer }}
                        </h4>
                    {% endif %}
                {% endfor %}
            </p>
            <h3>Up Voted Answers by me</h3>
            {% for answer in answers %}
                {% if answer.up_votes > 0 %}
                    <h4 class="card">Question: {{ answer.question.question_text }}<br><br>
                            Answer: {{ answer }}
                    </h4>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/register.html
{#{% extends 'dashboard/base.html' %}#}
{##}
{#{% load staticfiles %}#}
{##}
{#{% block css_block %}#}
{##}
{#{% endblock %}#}
{##}
{#{% block body %}#}
{#    {% include 'dashboard/homepage_header.html' %}#}
{#    <div class="container">#}
{#        <form method="post">#}
{#            {% csrf_token %}#}
{#                {{ user_form.as_p }}#}
{#            <input type="submit" class="btn btn-primary ask-question">#}
{#        </form>#}
{#    </div>#}
{##}
{#{% endblock %}#}

{% extends 'dashboard/base.html' %}


{% block body %}
    {% include 'dashboard/homepage_header.html' %}
    <section>

        <div class="top-content">
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 form-box">
                            <form action="" method="post" class="registration-form">


                                <div class="form-group">
                                    <fieldset>
                                        <div class="form-top">
                                            <div class="form-top-left">

                                                <h6 class="text-success">New Here?</h6>
                                                <h4 class="text-success">Register with us</h4>

                                            </div>
                                            <div class="form-top-right">
                                                <i class="fa fa-key"></i>
                                            </div>
                                        </div>

                                        <div class="form-bottom">
                                            <div class="form-group">
                                                {% csrf_token %}
                                                {% for field in user_form %}
                                                <p class="field-label">
                                                    {{ field.label }}:
                                                </p>
                                                <p class="field">
                                                    {{ field }}
                                                </p>
                                                {% endfor %}
                                            </div>
                                            <input type="submit" class="btn btn-next btn-primary btn-sm pull-right"><br>
                                        </div>
                                    </fieldset>
                                </div>

                            </form>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        </div>

    </section>
{% endblock %}

dashboard/templates/dashboard/stats.html
{% extends 'dashboard/base.html' %}

{% load staticfiles %}


{% block body %}
    {% include 'dashboard/homepage_header.html' %}
    <div class="container">
        <h2 class="text-success">See Upvoted answers in last hour and Most up voted answer</h2>
        <h3> Ordered by Highest Up voted answer in last hour</h3>
        {% for upvotes in upvoted_last_hour %}
            <div class="card">
                <h4 class="card-header">{{ upvotes.question.question_text }}</h4>
                <h4 class="card-header">{{ upvotes.answer_text }}</h4>
            </div><br>
        {% endfor %}
        <h3> Most Up Voted Answer</h3>
        {% for max_upvoted in max_upvoted_answers %}
            <div class="card">
                <h4 class="card-header">{{ max_upvoted.question.question_text }}</h4>
                <h4 class="card-header">{{ max_upvoted.answer_text }}</h4>
            </div><br>
        {% endfor %}
    </div>
{% endblock %}